env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GITHUB_ORG=onesrvnet
  #- DOCKER_ORG=libredesk

before:
  hooks:
    - go mod tidy
    - make frontend-build

builds:
  - id: "universal"
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos:
    #  - darwin
    #  - freebsd
      - linux
    #  - netbsd
    #  - openbsd
    #  - windows
    goarch:
      - amd64
    #  - arm64
    #  - arm
    #goarm:
    #  - 6
    #  - 7
    binary: 'libredesk{{ if eq .Os "windows" }}.exe{{ end }}'
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }}, {{ .Os }}/{{ .Arch }})" -X "main.versionString={{ .Tag }}"
    hooks:
      post: make stuff BIN={{ .Path }}

archives:
  - format: tar.gz
    name_template: 'libredesk_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if eq .Arch "arm" }}v{{ .Arm }}{{ end }}'
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "libredesk_{{ .Version }}_checksums.txt"

source:
  enabled: true
  format: tar.gz
  name_template: "libredesk_{{ .Version }}_source"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - universal
    image_templates:
     # - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:latest-amd64"
     # - "{{ .Env.DOCKER_ORG }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0
    dockerfile: Dockerfile
    extra_files:
      - config.sample.toml

docker_manifests:
  - name_template: ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:latest-amd64
  - name_template: ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_ORG }}/{{ .ProjectName }}:{{ .Tag }}-amd64

release:
  github:
    owner: onesrvnet
    name: libredesk
  prerelease: auto
  draft: true
